# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: creates output
      run:  pnpm i && npm run build # && echo "articles.jehy.ru" > public/CNAME    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Make changes and commit
      run: |
        # Example: Create a new file
        git add .
        git commit -m "make static"
    - name: Push changes
      run: git push origin HEAD:static --force